insert into company values('test1','testcom');

insert into employees values(employees_seq.nextval,'testdept','hanseong','남',to_date('2020-10-10','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept','hanseong','남',to_date('2020-10-10','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept','hanseong','남',to_date('2020-10-10','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept','hanseong','남',to_date('2020-10-10','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');
insert into employees values(employees_seq.nextval,'testdept2','hansung','여',to_date('2020-11-11','yyyy-mm-dd'),'test1');

commit


insert into managers values('testid',1234,1,'test1');

select * from company
select * from EMPLOYEES
